apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  annotations:
    argocd-image-updater/image-list: '["docker.io/yahav12321/k8stest"]'
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: yahav12321/k8stest:132
        ports:
        - containerPort: 8080
